# Generated by Django 4.2.7 on 2023-12-17 00:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=3857)),
                ('trip_distance', models.FloatField()),
                ('trip_time', models.FloatField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='rfid_sim.simulation')),
            ],
        ),
    ]
