# Generated by Django 4.2.7 on 2023-12-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_sim', '0003_delete_places_chipbuffer_intersection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidreader',
            name='route_count',
            field=models.IntegerField(null=True),
        ),
    ]
