# Generated by Django 4.2.7 on 2023-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_sim', '0004_rfidreader_route_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='run',
            field=models.BooleanField(default=False),
        ),
    ]
