# Generated by Django 4.2.7 on 2023-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_sim', '0005_simulation_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipbuffer',
            name='intersection_count',
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfidreader',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfidreader',
            name='chip_class',
            field=models.CharField(choices=[('Low Frequency', 'Low Frequency (2m)'), ('High Frequency', 'High Frequency (10m)'), ('Ultra High Frequency', 'Ultra High Frequency (100m)')], default='Low Frequency', max_length=32),
        ),
    ]
